//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeEstoque.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBControleEstoqueContainer : DbContext
    {
        public DBControleEstoqueContainer()
            : base("name=DBControleEstoqueContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PreProduto> PreProdutos { get; set; }
        public virtual DbSet<Produto> Produtos { get; set; }
        public virtual DbSet<Estoque> Estoque { get; set; }
        public virtual DbSet<Expedicao> Expedicao { get; set; }
        public virtual DbSet<OrdemFabricacao> OrdemFabricacao { get; set; }
    }
}
