//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeEstoque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        public Estoque()
        {
            this.QuantidadeProduzida = 0;
            this.QuantidadeDisponivel = 0;
            this.Expedicao = new HashSet<Expedicao>();
        }
    
        public string Lote { get; set; }
        public int ProdutoId { get; set; }
        public int QuantidadeProduzida { get; set; }
        public int QuantidadeDisponivel { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual ICollection<Expedicao> Expedicao { get; set; }
    }
}
