//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeEstoque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expedicao
    {
        public int Id { get; set; }
        public string EstoqueLote { get; set; }
        public int EstoqueProdutoId { get; set; }
        public System.DateTime Data { get; set; }
        public int Quantidade { get; set; }
    
        public virtual Estoque Estoque { get; set; }
    }
}
