//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeEstoque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemFabricacao
    {
        public OrdemFabricacao()
        {
            this.Envasado = false;
        }
    
        public int Id { get; set; }
        public string Lote { get; set; }
        public int PreProdutoId { get; set; }
        public System.DateTime Data { get; set; }
        public bool Envasado { get; set; }
        public Nullable<System.DateTime> DataProducao { get; set; }
    
        public virtual PreProduto PreProduto { get; set; }
    }
}
