//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeEstoque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreProduto
    {
        public PreProduto()
        {
            this.Produtos = new HashSet<Produto>();
            this.OrdensFabricacao = new HashSet<OrdemFabricacao>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sigla { get; set; }
    
        public virtual ICollection<Produto> Produtos { get; set; }
        public virtual ICollection<OrdemFabricacao> OrdensFabricacao { get; set; }
    }
}
