//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeEstoque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Estoque = new HashSet<Estoque>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Litros { get; set; }
        public Nullable<bool> Revenda { get; set; }
        public int PreProdutoId { get; set; }
    
        public virtual PreProduto PreProduto { get; set; }
        public virtual ICollection<Estoque> Estoque { get; set; }
    }
}
